variable "dataproc_cluster_name" { }
variable "region" { }
variable "project_name" { }
variable "staging_bucket" { }
variable "master_num_instance_number_node" { }
variable "master_machine_type" { }
variable "master_boot_disk_size_gb" { }
variable "worker_num_instances_number_node" { }
variable "worker_machine_type" { }
variable "worker_boot_disk_size_gb" { }
variable "zone" { }
variable "subnetwork" { }
variable "network_tags" { }
variable "service_acount" { }